init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "6"

platform:
  - x64
#  - x86

shallow_clone: true

install:
  - ps: .\scripts\server-setup.ps1
  - ps: Restart-Computer -Force
  - ps: Start-Sleep -s 10

build_script:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - npm test

deploy: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))