init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "6"

platform:
  - x64
  - x86

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - npm install
  - npm test

build: off
test: off
deploy: off
