init:
  - git config --global core.autocrlf true
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  matrix:
    - nodejs_version: "6"

platform:
  - x64
#  - x86

shallow_clone: true

install:
  - ps: |
      Install-windowsfeature -name AD-Domain-Services
      Install-ADDSForest –DomainName mycompany.local -SafeModeAdministratorPassword ConvertTo-SecureString -String "YX6oio7nHH+a)X1" -AsPlainText -Force

build_script:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - npm test

deploy: off
